name: Teste QA - API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Executar Testes Automatizados
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Permitir execução do Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar e executar testes (DEBUG)
        run: ./gradlew clean test --stacktrace --info --no-daemon

      - name: Listar artefatos gerados (após testes) - debug
        run: |
          echo ">>> pwd"
          pwd
          echo ">>> listar root"
          ls -la
          echo ">>> listar build (se existir)"
          ls -la build || true
          echo ">>> listar build/reports/tests/test (se existir)"
          ls -la build/reports/tests/test || true
          echo ">>> listar build/allure-results (se existir)"
          ls -la build/allure-results || true
          echo ">>> mostrar alguns arquivos (se existirem)"
          find build -maxdepth 4 -type f -print || true

      - name: Salvar Relatórios de Teste (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test/**

      - name: Salvar Allure Results (upload)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/**
