name: Teste QA - API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Executar Testes Automatizados
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ”§ Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: ğŸ§° Permitir execuÃ§Ã£o do Gradle Wrapper
        run: chmod +x ./gradlew

      - name: ğŸ“¦ Compilar e executar testes
        run: ./gradlew clean test --no-daemon

      - name: ğŸ“ Salvar RelatÃ³rios de Teste (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test/

      - name: ğŸ“ Salvar Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/
