name: Teste QA - API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Executar Testes Automatizados
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Permitir execução do Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar e executar testes
        run: ./gradlew clean test --no-daemon

      - name: Salvar Relatórios de Teste (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test/

      - name: Mostrar estrutura do build (debug)
        run: |
          echo ">>> pwd"
          pwd
          echo ">>> listar root"
          ls -la
          echo ">>> listar build"
          ls -la build || true
          echo ">>> listar build/reports/tests/test"
          ls -la build/reports/tests/test || true
          echo ">>> listar build/allure-results"
          ls -la build/allure-results || true
          echo ">>> mostrar alguns arquivos (se existirem)"
          find build/allure-results -maxdepth 1 -type f -print -exec head -n 5 {} \; || true

      - name: Salvar Allure Results (upload)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/**

